// <auto-generated />
namespace NAS.Storage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class change_structure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_structure));
        
        string IMigrationMetadata.Id
        {
            get { return "202502141057424_change_structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
